version: '3'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
